config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'
  root'pages#batman-vs-superman', to: "pages#batman_vs_superman"
  get 'pages/superman'
  post 'pages/submitb'
  post 'pages/submits'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/votos_batman.rb
class VotosBatman < ApplicationRecord
end

app/models/votos_superman.rb
class VotosSuperman < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  def page1
  end

  def page2
  end

  def page3
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end

  def submitb
  	# fail params.inspect
  	VotosBatman.create({name: params[:nameb], email: params[:emailb]})
  	redirect_to(pages_batman_path, notice: "Voto para Batman was saved")
  end
  
  def submits
  	# fail params.inspect
  	VotosSuperman.create({name: params[:names], email: params[:emails]})
  	redirect_to(pages_superman_path, notice: "Voto para Superman was saved")
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<h1>Experiments#page1</h1>
<p>Find me in app/views/experiments/page1.html.erb</p>

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Find me in app/views/experiments/page2.html.erb</p>

app/views/experiments/page3.html.erb
<h1>Experiments#page3</h1>
<p>Find me in app/views/experiments/page3.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Superheroes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class = "<%=  %>">
    <%= yield %>
  </body>
</html>

app/views/pages/batman-vs-superman.html.erb
<h1>¡¡¡!!!</h1>

<div class="batman">
	<a href="<%= asset_path 'batman.html'%>"><img src="<%= asset_path 'batman.jpg'%>"></a> 
	
	<%= form_tag(pages_submitb_path, method: "post", class: "form-horizontalb") do %>
		<div class="form-group">
			<label for="nameb" class="col-sm-2 control-label">Name</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" name="nameb" placeholder="Jane Doe">
			</div>
		</div>
		<div class="form-group">
			<label for="emailb" class="col-sm-2 control-label">Email</label>
			<div class="col-sm-10">
				<input type="email" class="form-control" name="emailb" placeholder="Email">
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
			 	<%= submit_tag("Voto a Batman", class: "btn btn-default") %>
			</div>
		</div>
	<% end %>
</div>

<div class="superman">
	<div>
		<a href="<%= asset_path 'superman.html'%>"><img src="<%= asset_path 'superman.jpg'%>"></a> 
	</div>
	<div>
	<%= form_tag(pages_submits_path, method: "post", class: "form-horizontals") do %>
			<div class="form-group">
				<label for="names" class="col-sm-2 control-label">Name</label>
				<div class="col-sm-10">
					<input type="text" class="form-control" name="names" placeholder="Jane Doe">
				</div>
			</div>
			<div class="form-group">
				<label for="emails" class="col-sm-2 control-label">Email</label>
				<div class="col-sm-10">
					<input type="email" class="form-control" name="emails" placeholder="Email">
				</div>
			</div>
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
				 	<%= submit_tag("Voto a Superman", class: "btn btn-default") %>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/pages/batman.html.erb
<h1>I Am Batman</h1>

app/views/pages/superman.html.erb
<h1>This looks like a job for Superman</h1>